# Generated by Django 5.2.4 on 2025-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuoi17', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='ho_ten',
        ),
        migrations.AddField(
            model_name='registration',
            name='ban_than',
            field=models.TextField(blank=True, null=True, verbose_name='Thành phần Bản thân'),
        ),
        migrations.AddField(
            model_name='registration',
            name='dan_toc',
            field=models.CharField(blank=True, null=True, verbose_name='Dân tộc'),
        ),
        migrations.AddField(
            model_name='registration',
            name='gioi_tinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=100, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ho_ten_cha',
            field=models.CharField(blank=True, null=True, verbose_name='Họ tên cha'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ho_ten_khai_sinh',
            field=models.CharField(blank=True, null=True, verbose_name='Họ tên khai sinh in hoa'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ho_ten_me',
            field=models.CharField(blank=True, null=True, verbose_name='Họ tên mẹ'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ho_ten_thuong_dung',
            field=models.CharField(blank=True, null=True, verbose_name='Họ và tên thường dùng'),
        ),
        migrations.AddField(
            model_name='registration',
            name='hoat_dong_16_den_nay',
            field=models.TextField(blank=True, null=True, verbose_name='Từ 16 tuổi đến nay làm gì'),
        ),
        migrations.AddField(
            model_name='registration',
            name='hoc_luc_11_15',
            field=models.CharField(blank=True, null=True, verbose_name='11-15 tuổi học trường gì'),
        ),
        migrations.AddField(
            model_name='registration',
            name='hoc_luc_6_11',
            field=models.CharField(blank=True, null=True, verbose_name='6-11 tuổi học trường gì'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nam_sinh_cha',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm sinh cha'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nam_sinh_me',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm sinh mẹ'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nghe_nghiep',
            field=models.CharField(blank=True, null=True, verbose_name='Nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nghe_nghiep_cha',
            field=models.CharField(blank=True, null=True, verbose_name='Nghề nghiệp (cha)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nghe_nghiep_me',
            field=models.CharField(blank=True, null=True, verbose_name='Nghề nghiệp (mẹ)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='noi_dang_ky_khai_sinh',
            field=models.CharField(blank=True, null=True, verbose_name='Nơi đăng ký khai sinh'),
        ),
        migrations.AddField(
            model_name='registration',
            name='noi_o_cha',
            field=models.CharField(blank=True, null=True, verbose_name='Nơi ở hiện tại của cha'),
        ),
        migrations.AddField(
            model_name='registration',
            name='noi_o_hien_tai',
            field=models.CharField(blank=True, null=True, verbose_name='Nơi ở hiện tại của bản thân'),
        ),
        migrations.AddField(
            model_name='registration',
            name='noi_o_me',
            field=models.CharField(blank=True, null=True, verbose_name='Nơi ở hiện tại của mẹ'),
        ),
        migrations.AddField(
            model_name='registration',
            name='noi_thuong_tru_gia_dinh',
            field=models.CharField(blank=True, null=True, verbose_name='Nơi thường trú của gia đình'),
        ),
        migrations.AddField(
            model_name='registration',
            name='que_quan',
            field=models.CharField(blank=True, null=True, verbose_name='Quê quán'),
        ),
        migrations.AddField(
            model_name='registration',
            name='quoc_tich',
            field=models.CharField(blank=True, null=True, verbose_name='Quốc tịch'),
        ),
        migrations.AddField(
            model_name='registration',
            name='so_anh_em',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gia đình có bao nhiêu anh chị em'),
        ),
        migrations.AddField(
            model_name='registration',
            name='so_cmnd_cccd',
            field=models.CharField(blank=True, null=True, verbose_name='Số CMND hoặc CCCD'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ten_anh_chi_em',
            field=models.TextField(blank=True, null=True, verbose_name='Tên anh chị em ruột'),
        ),
        migrations.AddField(
            model_name='registration',
            name='thanh_phan_gia_dinh',
            field=models.CharField(blank=True, null=True, verbose_name='Thành phần gia đình'),
        ),
        migrations.AddField(
            model_name='registration',
            name='tinh_trang_cha',
            field=models.CharField(blank=True, null=True, verbose_name='Tình trạng (cha)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='tinh_trang_me',
            field=models.CharField(blank=True, null=True, verbose_name='Tình trạng (mẹ)'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ton_giao',
            field=models.CharField(blank=True, null=True, verbose_name='Tôn giáo'),
        ),
        migrations.AddField(
            model_name='registration',
            name='trinh_do',
            field=models.CharField(blank=True, null=True, verbose_name='Trình độ học vấn'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tháng năm sinh'),
        ),
    ]
